name: drupal-lando-boilerplate
recipe: drupal8
config:
  webroot: www
  database: mysql
  php: 7.4
  via: apache
  drush: '*'
  xdebug: true
services:
  appserver:
    build:
      - composer install
      - >-
        /app/vendor/bin/phpcs --config-set installed_paths
        /app/vendor/drupal/coder/coder_sniffer
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  init-site:
    service: appserver
    cmd: >-
      chmod 555 .lando/settings/site_config.sh && chmod 555 .lando/scripts/init_site.sh && .lando/scripts/init_site.sh
    description: Initialize/Create/reinstall site.
  reinstall:
    service: appserver
    cmd: >-
      chmod 555 .lando/scripts/reinstall.sh && .lando/scripts/reinstall.sh
    description: Re install composer.
  local-sync:
    service: appserver
    cmd: >-
      chmod 555 .lando/scripts/local_sync.sh && .lando/scripts/local_sync.sh
    description: Update local environment.
  phpcs:
    service: appserver
    cmd: >-
      /app/vendor/bin/phpcs --standard=Drupal,DrupalPractice -p --colors ./www/modules/custom
    options: null
    description: Run phpcs to list all php code style evaluations.
  phpcs-fix:
    service: appserver
    cmd: >-
      /app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice -p --colors ./www/modules/custom
    options: null
    description: >-
      Run phpcsf to fix all php code style evaluations that can be fixed automatically.
  phpcs-summary:
    service: appserver
    cmd: >-
      /app/vendor/bin/phpcs --report=summary --standard=Drupal,DrupalPractice -p --colors ./www/modules/custom
    options: null
    description: Run phpcs to summary php code style evaluations.
