name: drupal-lando-boilerplate
recipe: drupal8
config:
  webroot: www
  database: mysql
  php: 7.4
  via: apache
  drush: '*'
  xdebug: true
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  reinstall:
    service: appserver
    cmd: >-
      echo "START REINSTALLATION ..." && rm -rf www/core && rm -rf www/modules/contrib && rm -rf www/themes/contrib && composer install && echo "END REINSTALLATION"
  local-sync:
      service: appserver
      cmd: >-
        echo "START LOCAL SYNCHRONOZATION ..." && composer install && chmod 555 scripts/local.sh && scripts/local.sh && echo "END LOCAL SYNCHRONOZATION"
